### ISSUE TITLE
Mauvais nommage des constantes de taille (ou mauvaises valeurs, c'est relatif)

### ISSUE THREAD

**Issue by KuiKui** [Innmind/Stream#1]
## Problème

Lors de l'utilisation de la lib dans une application, l'instruction suivante est sémantiquement fausse :

```php
if ($filesizeInByte > (5 * Size::MEGABYTES)) {
    ...
}
```

Car elle se transforme en :

```php
if ($filesizeInByte > (5 * 1024 ** 3)) { // soit 5 x 1073741824 soit 5Go
    ...
}
```

## Cause (probable)

L'unité _de base_ semble bien être [le byte](https://github.com/Innmind/Stream/blob/develop/src/Stream/Size.php#L27) mais la valeur de la constante ne semble pas être la bonne car elle sert de borne [strictement supérieure](https://github.com/Innmind/Stream/blob/develop/src/Stream/Size.php#L30) et est donc hors périmètre de ce que son nom indique.

## Solution

Diviser la valeur de toutes les constantes de taille par 1024 (et modifier le `switch` en conséquence).

## Remarque

Ajouter un test sur les constantes, c'est trop non ?
D'un autre coté, le problème aurait été vu s'il y avait un test 🤔

**Comment by Baptouuuu** [comment]
Effectivement les constantes définissent la borne supérieure. Leur nom ou la valeur ne peuvent pas être changée car il s'agirait d'un BC break.

Je verrais dans la prochaine version majeure comment adresser ce problème

**Comment by Baptouuuu** [comment]
La version `3.0` a supprimée ces constantes et introduit l'enum `Innmind\Stream\Stream\Size\Unit` qui permet d'écrire : 

```php
if ($filesizeInByte > (Unit::megabytes->times(5))) {
    ...
}
```
